const Product = require("./product");
const Category = require("./category");

// create table categories (id serial primary key, type varchar(255), parent varchar(255), "displayName" varchar(255), link text, image text);
const categories = [
    new Category("men", "men", "/men", null, "/img/categories/cat-men-1.jpg"),
    new Category(
        "men-half_shoes",
        "half shoes",
        "/men/half_shoes",
        "men",
        "/img/categories/cat-men-2.jpg"
    ),
    new Category(
        "men-boots",
        "boots",
        "/men/boots",
        "men",
        "/img/categories/cat-men-1.jpg"
    ),
    new Category(
        "men-sport_shoes",
        "sport shoes",
        "/men/sport_shoes",
        "men",
        "/img/categories/cat-men-2.jpg"
    ),

    new Category(
        "women",
        "women",
        "/women",
        null,
        "/img/categories/cat-women-2.jpg"
    ),
    new Category(
        "women-half_shoes",
        "half shoes",
        "/women/half_shoes",
        "women",
        "/img/categories/cat-women-1.jpg"
    ),
    new Category(
        "women-high_boots",
        "high boots",
        "/women/high_boots",
        "women",
        "/img/categories/cat-women-2.jpg"
    ),
    new Category(
        "women-ballerinas",
        "ballerinas",
        "/women/ballerinas",
        "women",
        "/img/categories/cat-women-1.jpg"
    ),
    new Category(
        "women-heel_shoes",
        "heel shoes",
        "/women/heel_shoes",
        "women",
        "/img/categories/cat-women-1.jpg"
    ),
    new Category(
        "women-sport_shoes",
        "sport shoes",
        "/women/sport_shoes",
        "women",
        "/img/categories/cat-women-1.jpg"
    ),

    new Category(
        "kids",
        "kids",
        "/kids",
        null,
        "/img/categories/cat-kids-1.jpg"
    ),
    new Category(
        "kids-half_shoes",
        "half shoes",
        "/kids/half_shoes",
        "kids",
        "/img/categories/cat-kids-2.jpg"
    ),
    new Category(
        "kids-sport_shoes",
        "sport shoes",
        "/kids/sport_shoes",
        "kids",
        "/img/categories/cat-kids-2.jpg"
    ),
    new Category(
        "kids-sandals",
        "sandals",
        "/kids/sandals",
        "kids",
        "/img/categories/cat-kids-1.jpg"
    ),
    new Category(
        "kids-ballerinas",
        "ballerinas",
        "/kids/ballerinas",
        "kids",
        "/img/categories/cat-kids-1.jpg"
    ),
];
// create table products (id serial primary key, category varchar(255), "productGroup" varchar(255), "displayName" varchar(255), description text, price real, color varchar(255), size varchar(255), image text, stock integer, tax real, reviews json[], "isPromoted" boolean, "isNew" boolean, discount numeric(2));
const products = [
    // Nike Air
    new Product(
        "men-sport_shoes",
        "Nike Air",
        "Nike Air",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-nike-air-grey.gif",
        "41",
        20,
        0.21,
        true,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Nike Air",
        "Nike Air",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-nike-air-grey.gif",
        "42",
        18,
        0.21,
        true,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Nike Air",
        "Nike Air",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-nike-air-grey.gif",
        "44",
        20,
        0.21,
        true,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Nike Air",
        "Nike Air",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-nike-air-grey.gif",
        "46",
        19,
        0.21,
        true,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Nike Air",
        "Nike Air",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-nike-air-grey.gif",
        "42",
        10,
        0.21,
        true,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Nike Air",
        "Nike Air",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-nike-air-grey.gif",
        "44",
        19,
        0.21,
        true,
        true
    ),

    // Nike Sport
    new Product(
        "men-sport_shoes",
        "Nike Sport",
        "Nike Sport",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-nike-sport-grey.gif",
        "41",
        20,
        0.21,
        true,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Nike Sport",
        "Nike Sport",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-nike-sport-grey.gif",
        "42",
        18,
        0.21,
        true,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Nike Sport",
        "Nike Sport",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-nike-sport-grey.gif",
        "44",
        20,
        0.21,
        true,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Nike Sport",
        "Nike Sport",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-nike-sport-grey.gif",
        "46",
        19,
        0.21,
        true,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Nike Sport",
        "Nike Sport",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-nike-sport-grey.gif",
        "42",
        10,
        0.21,
        true,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Nike Sport",
        "Nike Sport",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-nike-sport-grey.gif",
        "44",
        19,
        0.21,
        true,
        true
    ),

    // Glamour
    new Product(
        "men-half_shoes",
        "Glamour",
        "Glamour",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-glamour-brown.gif",
        "41",
        20,
        0.21,
        true,
        true
    ),
    new Product(
        "men-half_shoes",
        "Glamour",
        "Glamour",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-glamour-brown.gif",
        "42",
        18,
        0.21,
        true,
        true
    ),
    new Product(
        "men-half_shoes",
        "Glamour",
        "Glamour",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-glamour-brown.gif",
        "44",
        20,
        0.21,
        true,
        true
    ),
    new Product(
        "men-half_shoes",
        "Glamour",
        "Glamour",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-glamour-brown.gif",
        "46",
        19,
        0.21,
        true,
        true
    ),
    new Product(
        "men-half_shoes",
        "Glamour",
        "Glamour",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-glamour-brown.gif",
        "42",
        10,
        0.21,
        true,
        true
    ),
    new Product(
        "men-half_shoes",
        "Glamour",
        "Glamour",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/men-glamour-brown.gif",
        "44",
        19,
        0.21,
        true,
        true
    ),

    // Desert Nelli
    new Product(
        "men-boots",
        "Desert Nelli",
        "Desert Nelli",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-1.jpg",
        "41",
        20,
        0.21,
        false
    ),
    new Product(
        "men-boots",
        "Desert Nelli",
        "Desert Nelli",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-1.jpg",
        "42",
        18,
        0.21,
        false
    ),
    new Product(
        "men-boots",
        "Desert Nelli",
        "Desert Nelli",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-1.jpg",
        "44",
        20,
        0.21,
        false
    ),
    new Product(
        "men-boots",
        "Desert Nelli",
        "Desert Nelli",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-1.jpg",
        "46",
        19,
        0.21,
        false
    ),
    new Product(
        "men-boots",
        "Desert Nelli",
        "Desert Nelli",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-1.jpg",
        "42",
        10,
        0.21,
        false
    ),
    new Product(
        "men-boots",
        "Desert Nelli",
        "Desert Nelli",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        25,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-1.jpg",
        "44",
        19,
        0.21,
        false
    ),

    // Maya
    new Product(
        "men-sport_shoes",
        "Maya",
        "Maya",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        30,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-2.jpg",
        "41",
        20,
        0.21,
        false,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Maya",
        "Maya",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        30,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-2.jpg",
        "46",
        18,
        0.21,
        false,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Maya",
        "Maya",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        30,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-2.jpg",
        "44",
        20,
        0.21,
        false,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Maya",
        "Maya",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        30,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-2.jpg",
        "45",
        19,
        0.21,
        false,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Maya",
        "Maya",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        30,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-2.jpg",
        "42",
        10,
        0.21,
        false,
        true
    ),
    new Product(
        "men-sport_shoes",
        "Maya",
        "Maya",
        "Direct trade af typewriter next level. Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        30,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-2.jpg",
        "44",
        19,
        0.21,
        false,
        true
    ),

    // Half shoe Tom
    new Product(
        "men-half_shoes",
        "Half shoe Tom",
        "Half shoe Tom",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        20,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-3.jpg",
        "41",
        20,
        0.21,
        false,
        true
    ),
    new Product(
        "men-half_shoes",
        "Half shoe Tom",
        "Half shoe Tom",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        20,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-3.jpg",
        "46",
        18,
        0.21,
        false,
        true
    ),
    new Product(
        "men-half_shoes",
        "Half shoe Tom",
        "Half shoe Tom",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        20,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-3.jpg",
        "44",
        20,
        0.21,
        false,
        true
    ),
    new Product(
        "men-half_shoes",
        "Half shoe Tom",
        "Half shoe Tom",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        20,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-3.jpg",
        "45",
        19,
        0.21,
        false,
        true
    ),
    new Product(
        "men-half_shoes",
        "Half shoe Tom",
        "Half shoe Tom",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        20,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-3.jpg",
        "42",
        10,
        0.21,
        false,
        true
    ),
    new Product(
        "men-half_shoes",
        "Half shoe Tom",
        "Half shoe Tom",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        20,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/men/shoe-men-3.jpg",
        "44",
        19,
        0.21,
        false,
        true
    ),

    // Rootgard
    new Product(
        "women-sport_shoes",
        "Rootgard",
        "Rootgard",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-rootgard-blue.gif",
        "38",
        20,
        0.21,
        true,
        true
    ),
    new Product(
        "women-sport_shoes",
        "Rootgard",
        "Rootgard",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-rootgard-blue.gif",
        "39",
        18,
        0.21,
        true,
        true
    ),
    new Product(
        "women-sport_shoes",
        "Rootgard",
        "Rootgard",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-rootgard-blue.gif",
        "40",
        20,
        0.21,
        true,
        true
    ),
    new Product(
        "women-sport_shoes",
        "Rootgard",
        "Rootgard",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-rootgard-blue.gif",
        "41",
        19,
        0.21,
        true,
        true
    ),
    new Product(
        "women-sport_shoes",
        "Rootgard",
        "Rootgard",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-rootgard-blue.gif",
        "41",
        10,
        0.21,
        true,
        true
    ),
    new Product(
        "women-sport_shoes",
        "Rootgard",
        "Rootgard",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-rootgard-blue.gif",
        "40",
        19,
        0.21,
        true,
        true
    ),

    // Desert Boots
    new Product(
        "women-high_boots",
        "Desert Boots",
        "Desert Boots",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-boots-brown.gif",
        "38",
        20,
        0.21,
        true,
        true
    ),
    new Product(
        "women-high_boots",
        "Desert Boots",
        "Desert Boots",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-boots-brown.gif",
        "39",
        18,
        0.21,
        true,
        true
    ),
    new Product(
        "women-high_boots",
        "Desert Boots",
        "Desert Boots",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-boots-brown.gif",
        "40",
        20,
        0.21,
        true,
        true
    ),
    new Product(
        "women-high_boots",
        "Desert Boots",
        "Desert Boots",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-boots-brown.gif",
        "41",
        19,
        0.21,
        true,
        true
    ),
    new Product(
        "women-high_boots",
        "Desert Boots",
        "Desert Boots",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-boots-brown.gif",
        "41",
        10,
        0.21,
        true,
        true
    ),
    new Product(
        "women-high_boots",
        "Desert Boots",
        "Desert Boots",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-boots-brown.gif",
        "40",
        19,
        0.21,
        true,
        true
    ),

    // Audrey
    new Product(
        "women-heel_shoes",
        "Audrey",
        "Audrey",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-heel-audrey-granat.gif",
        "38",
        20,
        0.21,
        true,
        true
    ),
    new Product(
        "women-heel_shoes",
        "Audrey",
        "Audrey",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-heel-audrey-granat.gif",
        "39",
        18,
        0.21,
        true,
        true
    ),
    new Product(
        "women-heel_shoes",
        "Audrey",
        "Audrey",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-heel-audrey-granat.gif",
        "40",
        20,
        0.21,
        true,
        true
    ),
    new Product(
        "women-heel_shoes",
        "Audrey",
        "Audrey",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-heel-audrey-granat.gif",
        "41",
        19,
        0.21,
        true,
        true
    ),
    new Product(
        "women-heel_shoes",
        "Audrey",
        "Audrey",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-heel-audrey-granat.gif",
        "41",
        10,
        0.21,
        true,
        true
    ),
    new Product(
        "women-heel_shoes",
        "Audrey",
        "Audrey",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/women-heel-audrey-granat.gif",
        "40",
        19,
        0.21,
        true,
        true
    ),

    // Gracia
    new Product(
        "women-half_shoes",
        "Gracia",
        "Gracia",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/shoe-women-1.jpg",
        "38",
        20,
        0.21,
        false,
        true
    ),
    new Product(
        "women-half_shoes",
        "Gracia",
        "Gracia",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/shoe-women-1.jpg",
        "39",
        18,
        0.21,
        false,
        true
    ),
    new Product(
        "women-half_shoes",
        "Gracia",
        "Gracia",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/shoe-women-1.jpg",
        "40",
        20,
        0.21,
        false,
        true
    ),
    new Product(
        "women-half_shoes",
        "Gracia",
        "Gracia",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/shoe-women-1.jpg",
        "41",
        19,
        0.21,
        false,
        true
    ),
    new Product(
        "women-half_shoes",
        "Gracia",
        "Gracia",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/shoe-women-1.jpg",
        "41",
        10,
        0.21,
        false,
        true
    ),
    new Product(
        "women-half_shoes",
        "Gracia",
        "Gracia",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        23.96,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/shoe-women-1.jpg",
        "40",
        19,
        0.21,
        false,
        true
    ),
    // Passia
    new Product(
        "women-half_shoes",
        "Passia",
        "Passia",
        "Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        23.0,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/shoe-women-2.jpg",
        "38",
        20,
        0.21,
        true
    ),
    new Product(
        "women-half_shoes",
        "Passia",
        "Passia",
        "Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        23.0,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/shoe-women-2.jpg",
        "39",
        18,
        0.21,
        true
    ),
    new Product(
        "women-half_shoes",
        "Passia",
        "Passia",
        "Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        23.0,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/shoe-women-2.jpg",
        "40",
        20,
        0.21,
        true
    ),
    new Product(
        "women-half_shoes",
        "Passia",
        "Passia",
        "Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        23.0,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/shoe-women-2.jpg",
        "41",
        19,
        0.21,
        true
    ),
    new Product(
        "women-half_shoes",
        "Passia",
        "Passia",
        "Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        23.0,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/shoe-women-2.jpg",
        "41",
        10,
        0.21,
        true
    ),
    new Product(
        "women-half_shoes",
        "Passia",
        "Passia",
        "Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        23.0,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/shoe-women-2.jpg",
        "40",
        19,
        0.21,
        true
    ),
    // Georgia
    new Product(
        "women-ballerinas",
        "Georgia",
        "Georgia",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        49.0,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/ballerina-women-3.jpg",
        "38",
        20,
        0.21,
        true
    ),
    new Product(
        "women-ballerinas",
        "Georgia",
        "Georgia",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        49.0,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/ballerina-women-3.jpg",
        "39",
        18,
        0.21,
        true
    ),
    new Product(
        "women-ballerinas",
        "Georgia",
        "Georgia",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        49.0,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/ballerina-women-3.jpg",
        "40",
        20,
        0.21,
        true
    ),
    new Product(
        "women-ballerinas",
        "Georgia",
        "Georgia",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        49.0,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/ballerina-women-3.jpg",
        "41",
        19,
        0.21,
        true
    ),
    new Product(
        "women-ballerinas",
        "Georgia",
        "Georgia",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        49.0,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/ballerina-women-3.jpg",
        "41",
        10,
        0.21,
        true
    ),
    new Product(
        "women-ballerinas",
        "Georgia",
        "Georgia",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        49.0,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/women/ballerina-women-3.jpg",
        "40",
        19,
        0.21,
        true
    ),

    // Polly
    new Product(
        "kids-half_shoes",
        "Polly",
        "Polly",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        25.0,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-1.jpg",
        "27",
        20,
        0.21,
        true
    ),
    new Product(
        "kids-half_shoes",
        "Polly",
        "Polly",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        25.0,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-1.jpg",
        "26",
        18,
        0.21,
        true
    ),
    new Product(
        "kids-half_shoes",
        "Polly",
        "Polly",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        25.0,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-1.jpg",
        "29",
        20,
        0.21,
        true
    ),
    new Product(
        "kids-half_shoes",
        "Polly",
        "Polly",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        25.0,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-1.jpg",
        "31",
        19,
        0.21,
        true
    ),
    new Product(
        "kids-half_shoes",
        "Polly",
        "Polly",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        25.0,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-1.jpg",
        "28",
        10,
        0.21,
        true
    ),
    new Product(
        "kids-half_shoes",
        "Polly",
        "Polly",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        25.0,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-1.jpg",
        "30",
        19,
        0.21,
        true
    ),

    // Zumba
    new Product(
        "kids-half_shoes",
        "Zumba",
        "Zumba",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        25.0,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-1.jpg",
        "27",
        20,
        0.21,
        true
    ),
    new Product(
        "kids-half_shoes",
        "Zumba",
        "Zumba",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        25.0,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-1.jpg",
        "26",
        18,
        0.21,
        true
    ),
    new Product(
        "kids-half_shoes",
        "Zumba",
        "Zumba",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        25.0,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-1.jpg",
        "29",
        20,
        0.21,
        true
    ),
    new Product(
        "kids-half_shoes",
        "Zumba",
        "Zumba",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        25.0,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-1.jpg",
        "31",
        19,
        0.21,
        true
    ),
    new Product(
        "kids-half_shoes",
        "Zumba",
        "Zumba",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        25.0,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-1.jpg",
        "28",
        10,
        0.21,
        true
    ),
    new Product(
        "kids-half_shoes",
        "Zumba",
        "Zumba",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        25.0,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-1.jpg",
        "30",
        19,
        0.21,
        true
    ),

    // Peppa
    new Product(
        "kids-ballerinas",
        "Peppa",
        "Peppa",
        "Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        49.0,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-2.jpg",
        "27",
        20,
        0.21,
        false,
        true
    ),
    new Product(
        "kids-ballerinas",
        "Peppa",
        "Peppa",
        "Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        49.0,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-2.jpg",
        "26",
        18,
        0.21,
        false,
        true
    ),
    new Product(
        "kids-ballerinas",
        "Peppa",
        "Peppa",
        "Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        49.0,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-2.jpg",
        "29",
        20,
        0.21,
        false,
        true
    ),
    new Product(
        "kids-ballerinas",
        "Peppa",
        "Peppa",
        "Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        49.0,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-2.jpg",
        "31",
        19,
        0.21,
        false,
        true
    ),
    new Product(
        "kids-ballerinas",
        "Peppa",
        "Peppa",
        "Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        49.0,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-2.jpg",
        "28",
        10,
        0.21,
        false,
        true
    ),
    new Product(
        "kids-ballerinas",
        "Peppa",
        "Peppa",
        "Viral jean shorts hexagon, succulents vexillologist bicycle rights tumblr farm-to-table meditation tacos knausgaard irony portland dreamcatcher selfies.",
        49.0,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-2.jpg",
        "30",
        19,
        0.21,
        false,
        true
    ),

    // Goofy
    new Product(
        "kids-sandals",
        "Goofy",
        "Goofy",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        31.0,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-3.jpg",
        "27",
        20,
        0.21,
        true
    ),
    new Product(
        "kids-sandals",
        "Goofy",
        "Goofy",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        31.0,
        "#e5383b",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-3.jpg",
        "26",
        18,
        0.21,
        true
    ),
    new Product(
        "kids-sandals",
        "Goofy",
        "Goofy",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        31.0,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-3.jpg",
        "29",
        20,
        0.21,
        true
    ),
    new Product(
        "kids-sandals",
        "Goofy",
        "Goofy",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        31.0,
        "#f6da1c",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-3.jpg",
        "31",
        19,
        0.21,
        true
    ),
    new Product(
        "kids-sandals",
        "Goofy",
        "Goofy",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        31.0,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-3.jpg",
        "28",
        10,
        0.21,
        true
    ),
    new Product(
        "kids-sandals",
        "Goofy",
        "Goofy",
        "Celiac four dollar toast put a bird on it whatever austin lo-fi echo park paleo neutra banjo brooklyn sustainable. Mlkshk whatever prism iceland.",
        31.0,
        "#222",
        "https://michalantczakblogresources.s3.eu-central-1.amazonaws.com/goldenshoe/kids/shoe-kids-3.jpg",
        "30",
        19,
        0.21,
        true
    ),
];

module.exports = {
    categories,
    products,
};
