import {
  FaDocker,
  FaHtml5,
  FaCss3Alt,
  FaSass,
  FaNode,
  FaReact,
  FaLinux,
  FaGitSquare,
  FaFigma,
  FaJava,
  FaAws,
  FaAngular,
} from "react-icons/fa";
import {
  SiKubernetes,
  SiJavascript,
  SiNginx,
  SiMongodb,
  SiPostgresql,
  SiAmazondynamodb,
  SiWebpack,
  SiGraphql,
  SiTypescript,
  SiJest,
  SiCypress,
  SiVite
} from "react-icons/si";
import { ISkills } from "../../../types";

export const skills: ISkills[] = [
  {
    icon: FaHtml5,
    title: "HTML 5",
    description: "Expert in writing cross-browser, reusable markup with modern HTML5 semantics, including canvas and multimedia tags.",
    color: "skyblue",
    categories: ["all", "frontend"],
  },
  {
    icon: FaCss3Alt,
    title: "CSS 3",
    description: "Proficient in creating responsive layouts using Flexbox, Grid, and Floats. Enhances designs with animations and transitions. Skilled in BEM notation, styled-components, CSS modules, and CSS-in-JS.",
    color: "orangered",
    categories: ["all", "frontend"],
  },
  {
    icon: FaSass,
    title: "Sass",
    description: "Experienced with Sass, utilizing functions, mixins, interpolations, @content and @import directives, and the reference symbol '&'.",
    color: "violet",
    categories: ["all", "frontend"],
  },
  {
    icon: SiJavascript,
    title: "JavaScript",
    description: "Fluent in modern JavaScript (ECMAScript). Experienced in teaching JavaScript at Tech Accelerator sessions for new employees at AND Digital.",
    color: "goldenrod",
    categories: ["all", "frontend"],
  },
  {
    icon: FaAngular,
    title: "Angular",
    description: "Develops advanced front-end solutions with Angular, with a deep understanding of RXJS and Signal-based components.",
    color: "skyblue",
    categories: ["all", "frontend"],
  },
  {
    icon: FaReact,
    title: "React",
    description: "Skilled in both functional and class-based components, React Redux, React Router (contributor on GitHub), and related libraries. Experienced with Next.js and Gatsby.",
    color: "skyblue",
    categories: ["all", "frontend"],
  },
  {
    icon: FaNode,
    title: "NodeJs",
    description: "Proficient in using Node.js with Express to build RESTful APIs and backend functionalities.",
    color: "green",
    categories: ["all", "backend"],
  },
  {
    icon: SiNginx,
    title: "Nginx",
    description: "Experienced in using Nginx as a reverse proxy and backend server to handle incoming requests efficiently.",
    color: "darkgreen",
    categories: ["all", "backend"],
  },
  {
    icon: FaLinux,
    title: "Linux",
    description: "Skilled in working with Linux-based Virtual Private Servers, with knowledge of system structure, commands, and basic Bash scripting.",
    color: "#f2f2f2",
    categories: ["all", "backend", "devops"],
  },
  {
    icon: SiMongodb,
    title: "MongoDB",
    description: "Proficient in MongoDB, with extensive experience using Mongoose ODM for database management.",
    color: "#4db33d",
    categories: ["all", "backend"],
  },
  {
    icon: SiPostgresql,
    title: "PostgreSQL",
    description: "Fluent in PostgreSQL, skilled in table creation, data manipulation, transactions, and advanced SQL syntax.",
    color: "skyblue",
    categories: ["all", "backend"],
  },
  {
    icon: SiAmazondynamodb,
    title: "DynamoDB",
    description: "Thorough understanding of DynamoDB for serverless applications, with extensive usage experience.",
    color: "dodgerblue",
    categories: ["all", "backend", "serverless"],
  },
  {
    icon: FaGitSquare,
    title: "Git",
    description: "Master of Git, proficient in all operations. Experienced in building CI/CD pipelines with GitHub Actions, AWS CodeBuild. Worked with GitHub, GitLab, and CodeCommit.",
    color: "orangered",
    categories: ["all", "backend", "frontend", "devops"],
  },
  {
    icon: FaFigma,
    title: "Figma",
    description: "Designs projects using Figma, a modern tool similar to Sketch and Adobe XD.",
    color: "plum",
    categories: ["all", "frontend"],
  },
  {
    icon: SiWebpack,
    title: "Webpack 5",
    description: "Experienced with Webpack, understanding loaders, plugins, proxies, and building modern JavaScript applications.",
    color: "skyblue",
    categories: ["all", "frontend"],
  },
  {
    icon: SiVite,
    title: "Vite",
    description: "Proficient in using Vite to build fast and modern JavaScript applications with an optimized development experience.",
    color: "darkgreen",
    categories: ["all", "frontend"],
  },
  {
    icon: SiGraphql,
    title: "GraphQL",
    description: "Proficient in GraphQL, experienced with both frontend (Apollo Client) and backend (Apollo Server) implementations.",
    color: "violet",
    categories: ["all", "frontend", "backend"],
  },
  {
    icon: SiTypescript,
    title: "TypeScript",
    description: "Expert in TypeScript, understanding its concepts of data types, interfaces, and enhanced development experience.",
    color: "#3970e4",
    categories: ["all", "frontend", "backend"],
  },
  {
    icon: SiJest,
    title: "Jest",
    description: "Primarily uses Jest for unit testing on both backend and frontend with React Testing Library.",
    color: "orangered",
    categories: ["all", "frontend", "backend"],
  },
  {
    icon: SiCypress,
    title: "Cypress",
    description: "Main tool for end-to-end testing of applications, ensuring comprehensive test coverage.",
    color: "#4db33d",
    categories: ["all", "frontend"],
  },
  {
    icon: FaDocker,
    title: "Docker",
    description: "Develops and manages container images with Docker, utilizing Docker Compose, AWS ECS, and Fargate.",
    color: "skyblue",
    categories: ["all", "devops", "backend"],
  },
  {
    icon: SiKubernetes,
    title: "Kubernetes",
    description: "Manages container orchestration with Kubernetes, deploying, and managing pods and services using AWS EKS and Fargate.",
    color: "#3970e4",
    categories: ["all", "devops", "backend"],
  },
  {
    icon: FaJava,
    title: "JAVA",
    description: "Good understanding of Java, focusing on Object-Oriented programming and building applications with Spring Boot framework.",
    color: "orangered",
    categories: ["all", "backend"],
  },
  {
    icon: FaAws,
    title: "Lambda",
    description: "Utilizes AWS Lambda for serverless architecture, implementing efficient serverless functions.",
    color: "goldenrod",
    categories: ["all", "backend", "serverless"],
  },
  {
    icon: FaAws,
    title: "API Gateway",
    description: "Experienced with AWS API Gateway for creating and managing REST APIs within serverless architectures.",
    color: "goldenrod",
    categories: ["all", "backend", "serverless"],
  },
  {
    icon: FaAws,
    title: "SAM model",
    description: "Skilled in writing and managing AWS CloudFormation templates as part of the AWS Serverless Application Model (SAM).",
    color: "goldenrod",
    categories: ["all", "devops", "serverless"],
  },
  {
    icon: FaAws,
    title: "AWS CDK",
    description: "Skilled in writing and managing AWS CloudFormation templates with AWS CDK library.",
    color: "goldenrod",
    categories: ["all", "devops", "serverless"],
  },
];

